services:
  - type: web
    name: techsisters-bookclub
    runtime: docker
    plan: free # or starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: HCAPTCHA_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: WHATSAPP_GROUP_LINK
        sync: false
    healthCheckPath: /health
